autentikasi/urls.py
from django.urls import path
from .views import signup, signin, signout

app_name = 'autentikasi'

urlpatterns = [
    path('signin/', signin, name="signin"),
    path('signup/', signup, name="signup"),
    path('signout/', signout, name="signout"),
]

homepage/urls.py
from django.urls import path
from .views import index, add_note

app_name = 'homepage'

urlpatterns = [
    path('', index, name="index"),
    path('add_note/', add_note, name="add_note")
]

note/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from homepage import urls as homepage_urls
from autentikasi import urls as autentikasi_urls
from todo import urls as todo_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(homepage_urls)),
    path('autentikasi/', include(autentikasi_urls)),
    path('todo/', include(todo_urls)),
]

todo/urls.py
from django.urls import path
from .views import *

app_name = "todo"

urlpatterns = [
    path("", index, name="index"),
    path("api/", get_todos, name="api_todo"),
    path("add/", add_todo, name="add_todo"),
    path("delete/<str:todo_id>", delete_todo, name="delete_todo"),
]

autentikasi/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models

# Create your models here.

class Note(models.Model):
    title = models.CharField(max_length=100)
    datetime = models.DateTimeField()
    content = models.TextField()
    
    def __str__(self) -> str:
        return f"{self.title} - {self.datetime}"

todo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class ToDo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    deadline = models.DateTimeField()
    text = models.CharField(max_length=150)

    def __str__(self):
        return f"{self.user.username} | {self.text}"

homepage/forms.py
from django.forms import ModelForm

from homepage.models import Note

class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'datetime', 'content']

todo/forms.py
from django.forms import ModelForm, widgets
from django.forms.widgets import Input
from .models import ToDo

class TodoForm(ModelForm):
    class Meta:
        model = ToDo
        fields = "__all__"
        widgets = {
            "deadline": Input(attrs={"type": "datetime-local", "class": "form-control"}),
            "text": Input(attrs={"class": "form-control"}),
        }

autentikasi/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("autentikasi:signin")
        return render(request, "autentikasi/signup.html")
    else:
        return render(request, "autentikasi/signup.html")

def signin(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("homepage:index")
        return render(request, "autentikasi/signin.html")
    else:
        return render(request, "autentikasi/signin.html")

def signout(request):
    logout(request)
    return redirect("homepage:index")

homepage/views.py
from django.shortcuts import render, redirect

from homepage.forms import NoteForm
from .models import Note
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    notes = Note.objects.all()
    data = {"daftar_note": notes}
    return render(request, template_name="homepage/index_with_bootstrap.html", context=data)

# @login_required(login_url="autentikasi:signin")
# def add_note(request):
#     if request.method == "POST":
#         title = request.POST["title"]
#         datetime = request.POST["datetime"]
#         content = request.POST["content"]
#         Note.objects.create(
#             title=title,
#             datetime=datetime,
#             content=content
#         )
#     return redirect("homepage:index")

@login_required(login_url="autentikasi:signin")
def add_note(request):
    if request.method == "POST":
        form = NoteForm(request.POST)
        if form.is_valid():
            form.save()
    return redirect("homepage:index")

todo/views.py
from typing import final
from django.shortcuts import redirect, render

from todo.forms import TodoForm
from .models import ToDo
from django.core import serializers
from django.http.response import HttpResponse
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required(login_url="autentikasi:signin")
def index(request):
    return render(request, "todo/index.html")

@login_required(login_url="autentikasi:signin")
def get_todos(request):
    todos = ToDo.objects.all()
    todos_json = serializers.serialize("json", todos)
    return HttpResponse(todos_json, content_type="application/json")

@login_required(login_url="autentikasi:signin")
def add_todo(request):
    form = TodoForm()
    if request.method == "POST":
        data = request.POST.dict()
        data["user"] = request.user
        form = TodoForm(data)
        if form.is_valid():
            form.save()
            return redirect("todo:index")
    context = {"form": form}
    return render(request, "todo/add_todo.html", context)


@login_required(login_url="autentikasi:signin")
def delete_todo(request, todo_id):
    try:
        ToDo.objects.get(id=todo_id).delete()
    except Exception as e:
        print(e)
    finally:
        return redirect("todo:index")

autentikasi/templates/autentikasi/signin.html
{% extends 'base.html' %}
{% block content %}
<h1>Sign In</h1>

    <form action="{% url 'autentikasi:signin' %}" method="POST">
      {% csrf_token %}
      <div class="mb-3">
        <label for="email" class="form-label">Email address</label>
        <input type="email" class="form-control" id="email" name="username">
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
      </div>
      <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" id="password" name="password">
      </div>

      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock content %}

autentikasi/templates/autentikasi/signup.html
{% extends 'base.html' %}
{% block content %}
<h1>Sign Up</h1>

<form action="{% url 'autentikasi:signup' %}" method="POST">
  {% csrf_token %}
  <div class="mb-3">
    <label for="email" class="form-label">Email address</label>
    <input type="email" class="form-control" id="email" name="username">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="password1" class="form-label">Password</label>
    <input type="password" class="form-control" id="password1" name="password1">
  </div>
  <div class="mb-3">
    <label for="password2" class="form-label">Ulangi Password</label>
    <input type="password" class="form-control" id="password2" name="password2">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

homepage/templates/homepage/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'homepage/css/style.css' %}">
  <title>My Application</title>
</head>
<body>
  <header>
    <img src="{% static 'homepage/images/note.jpg' %}" alt="Note">
  </header>
  {% for note in daftar_note %}
    <h4> {{ note.title }} </h4>
    <p> {{ note.content }} </p>
    <hr>
  {% endfor %}
</body>
</html>

homepage/templates/homepage/index_with_bootstrap.html
{% extends 'base.html' %}

{% block head %}
  <title>Homepage</title>
{% endblock head %}

{% block content %}
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Datetime</th>
        <th scope="col">Content</th>
      </tr>
    </thead>
    <tbody>
      {% for note in daftar_note %}
      <tr>
        <td>{{ note.title }}</td>
        <td>{{ note.datetime }}</td>
        <td>{{ note.content }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>


  <!-- Button trigger modal -->
  {% if user.is_authenticated %}
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Create new Note
  </button>
  {% endif %}

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Create new Note</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="{% url 'homepage:add_note' %}" method="post">
            {% csrf_token %}
            <div class="mb-3">
              <label for="title" class="form-label">Title</label>
              <input type="text" class="form-control" id="title" name="title">
            </div>
            <div class="mb-3">
              <label for="datetime" class="form-label">Datetime</label>
              <input type="date" class="form-control" id="datetime" name="datetime">
            </div>
            <div class="mb-3">
              <label for="content" class="form-label">Content</label>
              <input type="text" class="form-control" id="content" name="content">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'style.css' %}">


  {% block head %}
  {% endblock head %}
</head>

<body>
  {% include 'navbar.html' %}
  {% block content %}

  {% endblock content %}

  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  {% block js %}
  {% endblock js %}
</body>

</html>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'homepage:index' %}">
      <img src="{% static 'homepage/images/sticky-notes.svg' %}" height="32px" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'homepage:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'todo:index' %}">Todo</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'autentikasi:signout' %}">Sign Out</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'autentikasi:signin' %}">Sign In</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'autentikasi:signup' %}">Sign Up</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

todo/templates/todo/add_todo.html
{% extends 'base.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'todo/add_todo.css' %}">
  <title>Add Todo</title>
{% endblock head %}

{% block content %}
<div class="container" id="todo">
  <form action="" method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label class="form-label">Deadline</label>
      {{ form.deadline }}
    </div>
    <div class="mb-3">
      <label class="form-label">Text</label>
      {{ form.text }}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock content %}

todo/templates/todo/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container">
  {% csrf_token %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Todo</th>
        <th scope="col">Deadline</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody id="todo-data">
    </tbody>
  </table>
  <div class="d-flex justify-content-center mt-5">
    <a href="{% url 'todo:add_todo' %}">
      <button class="btn btn-primary">Add Todo</button>
    </a>
  </div>
</div>

<div class="container">
  {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Deadline</label>
    <input class="form-control" type="datetime-local" id="input-deadline">
  </div>
  <div class="mb-3">
    <label class="form-label">Text</label>
    <input class="form-control" type="text" id="input-text">
  </div>
  <button id="update-btn" type="submit" class="btn btn-primary">Submit</button>
</div>
{% endblock content %}

{% block js %}
<script src="{% static 'todo/script.js' %}"></script>
{% endblock js %}